In [7]:
"""
Task 1 - (1) : Write a function to compute 5/0 and use try/except to catch the exceptions
"""
def divide(x, y):
    try:
        x/y
    except ZeroDivisionError as ze:
        print("Dividing a number by ZERO exception")
    except:
        print("Any other exception")

divide(5, 0)

Dividing a number by ZERO exception


In [5]:
"""
Task 1 - (2) : Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
"""
subject = ["Americans", "Indians"]
verb = ["Play", "watch"]
obj = ["Baseball","cricket"]

# List Comprehension
sentence_list = [(sub + " " + vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
    print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [15]:
"""
Task 2 - (1) : Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, 
the i-th output column is the input vector raised element-wise to the power of N - i - 1.
"""
import numpy as num_py

def gen_vander_matrix(input_vector, n, bool_arg=False):
    '''This function Will return Matrix in which the columns of the output matrix are powers of the input vector.'''    
    return num_py.vander(x=input_vector, N=n, increasing=bool_arg)

# input paramater
input_vector = num_py.arange(2, 10, 2)   # input vector (1-D array)
n = 4                                    # no. of column in matrix 

# function execution
out_matrix_True = gen_vander_matrix(input_vector, n, True)
out_matrix_False = gen_vander_matrix(input_vector, n, False)

#output
print("Input vector:\n", input_vector, "\n")
print("Output Matrix (Increasing = True):\n", out_matrix_True, "\n")
print("Output Matrix (Increasing = False):\n", out_matrix_False)

Input vector:
 [2 4 6 8] 

Output Matrix (Increasing = True):
 [[  1   2   4   8]
 [  1   4  16  64]
 [  1   6  36 216]
 [  1   8  64 512]] 

Output Matrix (Increasing = False):
 [[  8   4   2   1]
 [ 64  16   4   1]
 [216  36   6   1]
 [512  64   8   1]]
